In [1]:
import numpy as np
import pandas as pd
#import keras
import tensorflow as tf

In [2]:
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Flatten
from tensorflow.keras.layers import LSTM, GRU, SimpleRNN
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [3]:
data3 = """ Tab Rasode me kaun tha\n
		Tum thi ? mai thi?kaun tha?\n
		Rashi Thi\n
		Tab Rashi ne Kuckar me se chanee nikal diyaa
		aur kahlee kucker gas pe chadd diyaa\n """

In [4]:
data = """ Jack and Jill went up the hill\n
		To fetch a pail of water\n
		Jack fell down and broke his crown\n
		And Jill came tumbling after\n """

In [5]:
data1 = ['How are you today',
         'What are you doing today',
         'How is your day today',
         'What are your plans today']

In [6]:
data2 = ['Well done!',
		'Good work',
		'Great effort',
		'nice work',
		'Excellent!']

In [7]:
data1

['How are you today',
 'What are you doing today',
 'How is your day today',
 'What are your plans today']

In [8]:
token = Tokenizer()
token.fit_on_texts([data])
encoded = token.texts_to_sequences([data])[0]
#tokenizer.fit_on_texts(data2)
#encode1 = token.texts_to_matrix(data1, mode='count')
print(len(encoded))
print(data)

25
 Jack and Jill went up the hill

		To fetch a pail of water

		Jack fell down and broke his crown

		And Jill came tumbling after
 


In [9]:
#print(token.word_counts)

In [10]:
#token.document_count

In [11]:
#token.word_index

In [12]:
#token.word_docs

In [13]:
#print(encode1)

In [14]:
vocab_size = len(token.word_index) + 1
print('Vocabulary Size: %d' % vocab_size)

Vocabulary Size: 22


In [15]:
sequences = list()

In [16]:
for i in range(1, len(encoded)):
	sequence = encoded[i-1:i+15]
	sequences.append(sequence)
print('Total Sequences: %d' % len(sequences))
print(sequences)

Total Sequences: 24
[[2, 1, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 2, 14, 15], [1, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 2, 14, 15, 1], [3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 2, 14, 15, 1, 16], [4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 2, 14, 15, 1, 16, 17], [5, 6, 7, 8, 9, 10, 11, 12, 13, 2, 14, 15, 1, 16, 17, 18], [6, 7, 8, 9, 10, 11, 12, 13, 2, 14, 15, 1, 16, 17, 18, 1], [7, 8, 9, 10, 11, 12, 13, 2, 14, 15, 1, 16, 17, 18, 1, 3], [8, 9, 10, 11, 12, 13, 2, 14, 15, 1, 16, 17, 18, 1, 3, 19], [9, 10, 11, 12, 13, 2, 14, 15, 1, 16, 17, 18, 1, 3, 19, 20], [10, 11, 12, 13, 2, 14, 15, 1, 16, 17, 18, 1, 3, 19, 20, 21], [11, 12, 13, 2, 14, 15, 1, 16, 17, 18, 1, 3, 19, 20, 21], [12, 13, 2, 14, 15, 1, 16, 17, 18, 1, 3, 19, 20, 21], [13, 2, 14, 15, 1, 16, 17, 18, 1, 3, 19, 20, 21], [2, 14, 15, 1, 16, 17, 18, 1, 3, 19, 20, 21], [14, 15, 1, 16, 17, 18, 1, 3, 19, 20, 21], [15, 1, 16, 17, 18, 1, 3, 19, 20, 21], [1, 16, 17, 18, 1, 3, 19, 20, 21], [16, 17, 18, 1, 3, 19, 20, 21], [17, 18, 1, 3, 19, 20, 21], [18, 1,

In [17]:
sequences=tf.keras.preprocessing.sequence.pad_sequences(sequences,maxlen=15, padding="post")
#print(sequences)

In [18]:
sequences = np.array(sequences)
print(sequences[:])
X, y = sequences[:,0],sequences[:,1]
print(y)

[[ 1  3  4  5  6  7  8  9 10 11 12 13  2 14 15]
 [ 3  4  5  6  7  8  9 10 11 12 13  2 14 15  1]
 [ 4  5  6  7  8  9 10 11 12 13  2 14 15  1 16]
 [ 5  6  7  8  9 10 11 12 13  2 14 15  1 16 17]
 [ 6  7  8  9 10 11 12 13  2 14 15  1 16 17 18]
 [ 7  8  9 10 11 12 13  2 14 15  1 16 17 18  1]
 [ 8  9 10 11 12 13  2 14 15  1 16 17 18  1  3]
 [ 9 10 11 12 13  2 14 15  1 16 17 18  1  3 19]
 [10 11 12 13  2 14 15  1 16 17 18  1  3 19 20]
 [11 12 13  2 14 15  1 16 17 18  1  3 19 20 21]
 [11 12 13  2 14 15  1 16 17 18  1  3 19 20 21]
 [12 13  2 14 15  1 16 17 18  1  3 19 20 21  0]
 [13  2 14 15  1 16 17 18  1  3 19 20 21  0  0]
 [ 2 14 15  1 16 17 18  1  3 19 20 21  0  0  0]
 [14 15  1 16 17 18  1  3 19 20 21  0  0  0  0]
 [15  1 16 17 18  1  3 19 20 21  0  0  0  0  0]
 [ 1 16 17 18  1  3 19 20 21  0  0  0  0  0  0]
 [16 17 18  1  3 19 20 21  0  0  0  0  0  0  0]
 [17 18  1  3 19 20 21  0  0  0  0  0  0  0  0]
 [18  1  3 19 20 21  0  0  0  0  0  0  0  0  0]
 [ 1  3 19 20 21  0  0  0  0  0  0  0  0

In [19]:
#X

In [20]:
#y

In [21]:
y = to_categorical(y, num_classes=vocab_size)

In [22]:
# define model
model = Sequential()
model.add(Embedding(vocab_size, 10, input_length=1))

In [23]:
model.add(LSTM(50, activation='relu'))
model.add(Dense(vocab_size, activation='softmax'))
print(model.summary())

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 1, 10)             220       
_________________________________________________________________
lstm (LSTM)                  (None, 50)                12200     
_________________________________________________________________
dense (Dense)                (None, 22)                1122      
Total params: 13,542
Trainable params: 13,542
Non-trainable params: 0
_________________________________________________________________
None


In [24]:
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
# fit network
model.fit(X, y, epochs=500, verbose=1)

Epoch 1/500
1/1 [==============================] - 1s 1s/step - loss: 3.0912 - accuracy: 0.0000e+00
Epoch 2/500
1/1 [==============================] - 0s 14ms/step - loss: 3.0906 - accuracy: 0.0000e+00
Epoch 3/500
1/1 [==============================] - 0s 15ms/step - loss: 3.0899 - accuracy: 0.0833
Epoch 4/500
1/1 [==============================] - 0s 14ms/step - loss: 3.0893 - accuracy: 0.1250
Epoch 5/500
1/1 [==============================] - 0s 12ms/step - loss: 3.0887 - accuracy: 0.1250
Epoch 6/500
1/1 [==============================] - 0s 13ms/step - loss: 3.0881 - accuracy: 0.1250
Epoch 7/500
1/1 [==============================] - 0s 14ms/step - loss: 3.0875 - accuracy: 0.1250
Epoch 8/500
1/1 [==============================] - 0s 13ms/step - loss: 3.0869 - accuracy: 0.1250
Epoch 9/500
1/1 [==============================] - 0s 12ms/step - loss: 3.0863 - accuracy: 0.1250
Epoch 10/500
1/1 [==============================] - 0s 12ms/step - loss: 3.0857 - accuracy: 0.1250
Epoch 11/500


# Text Prediction

In [25]:
n_words = 15
text_test = 'Jack'
result = 'Jack'

In [26]:
for _ in range(n_words):
    encoded = token.texts_to_sequences([text_test])[0]
    encoded = np.array(encoded)
    # predict a word in the vocabulary
    y_Predict = model.predict_classes(encoded, verbose=0)
    Next_word = ''
    for word, index in token.word_index.items():
        if index == y_Predict:
            Next_word = word
            break
    text_test, result = Next_word, result + ' ' + Next_word

C:\Users\Dr.PVVK\AppData\Roaming\Python\Python38\site-packages\tensorflow\python\keras\engine\sequential.py:455: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


In [27]:
print(result)

Jack fell down and jill went up the hill to fetch a pail of water jack
